name: Firebase Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Verify files
      run: |
        echo "Listing root directory:"
        ls -la
        echo "Listing app directory:"
        ls -la ./app

    - name: Install dependencies
      run: npm install
      working-directory: ./app

    - name: Build React app
      run: npx react-scripts build
      working-directory: ./app

    - name: Move build to Firebase folder
      run: mv ./app/build ./buklodwebbapp
