name: Firebase Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2️⃣ Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # 3️⃣ Verify files (optional, for debugging)
    - name: Verify files
      run: |
        echo "Root directory contents:"
        ls -la
        echo "App directory contents:"
        ls -la ./app

    # 4️⃣ Install dependencies inside `app/`
    - name: Install dependencies
      run: npm ci
      working-directory: ./app

    # 5️⃣ Build React app inside `app/`
    - name: Build React app
      run: npx react-scripts build
      working-directory: ./app

    # 6️⃣ Move build output to Firebase folder
    - name: Move build to Firebase folder
      run: mv ./app/build ./buklodwebbapp

    # 7️⃣ Deploy to Firebase Hosting
    - name: Deploy to Firebase Hosting
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: "${{ secrets.GITHUB_TOKEN }}"
        projectId: "buklod-connect"
        channelId: "live"
