name: Firebase Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Verify files
      run: |
        echo "Listing root directory:"
        ls -la
        echo "Listing app directory:"
        ls -la ./app

    - name: Install dependencies
      working-directory: ./app
      run: npm ci

    - name: Build React app
      working-directory: ./app
      run: |
        npx react-scripts build
        mv build ../buklodwebbapp

    - name: Deploy to Firebase Hosting
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: "${{ secrets.GITHUB_TOKEN }}"
        projectId: "buklod-connect"
        channelId: "live"
